import type { Metadata, Viewport } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){function setVvh(){var h=(window.visualViewport?window.visualViewport.height:window.innerHeight)*0.01;document.documentElement.style.setProperty('--vvh',h+'px');}setVvh();window.addEventListener('resize',setVvh);if(window.visualViewport){window.visualViewport.addEventListener('resize',setVvh);}})();`,
          }}
        />
        <link
          rel="preload"
          as="image"
          href="/textures/grass_pattern.png"
        />
        <link
          rel="preload"
          as="fetch"
          href="/rive/remy_home_sm.riv"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
